### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by dcblogdev** [nova-framework/mini-router#2]
```php
DB::select('select * from '.PREFIX.'posts');
```

Results in:

```php
Call to a member function fetchAll() on boolean in /Users/davidcarr/Desktop/mini/system/Database/Connection.php on line 105
```

**Comment by LuckyCyborg** [comment]
OK, I've not tested yet the Database part. BUT, good to know.

The priority was implementing that Exceptions Handler, with no external dependencies, and being PHP56 and PHP7 compatible. ;)

**Comment by LuckyCyborg** [comment]
Updated. Please test.

**Comment by dcblogdev** [comment]
works 👍
