### ISSUE TITLE
Router x native server file system

### ISSUE THREAD

**Issue by ghost** [nova-framework/mini-router#3]
would not it be more interesting to take advantage of the server's native file system instead of creating another router?

**Comment by dcblogdev** [comment]
I understand but is actually for a standalone project isolated from the rest of the repo's here.

**Comment by LuckyCyborg** [comment]
@aicoutos Despite the repository name, this project actually is a miniature **MVC framework**, written for (particular) education purposes.

Even if we talk about the Router part, on its under 5KB size, it  gives you features like named parameters, optional parameters, handling all HTTP methods, executing of Controllers and Closures, and so on...

Yet, there is also a View which is able to give you a Fluent interface, and also can give you, on its miniature size, enough support to get something like:

```php
$view = View::make('Layouts/Default')
    ->nest('content', 'Default', compact('content'))
    ->shares('title', 'Whoops!');

echo $view->render();
```
This one will render a page with a master layout View, aka *theming*.

And, of course the Model part is represented, by a mini Database API, which gives you even a QueryBuilder, then you can do:
```php
$result = DB::table('users')->where('id', $userId)->update(array(
    'username'  => 'testuser2',
    'password'  => 'another password',
    'realname'  => 'Updated Test User',
    'email'     => 'test@testuser.dev',
    'activated' => 1,
));
```
OR
```php
$users = DB::table('users')->where('activated', 1)->offset(40)->limit(10)->get();
```
Finally, there is even a support for `Events`. 

So, one can even write a real site using this "mini router" if he can live with its minimal APIs ... 😈 

PS. I hope that we all agree to close this issue, as the "native server file system" is not on the purposes of this particular project, even by a far shoot.
